### ISSUE TITLE
Retained backing issues

### ISSUE THREAD

**Issue by lcarrettin** [kakashidinho/metalangle#11]
Hi,
First of all thanks for your work.
I should port a project which needs the retained backing feature, so I started with the MGLPaint sample as a reference.
I faced two issues:

1) I’m testing on simulators and the app only displays its content on version 13.+. Blank screen on previous versions.

2) If you enable GL_SCISSOR_TEST inside the rendering function (and don’t disable it before the [glLayer present] call) the screen flickers apparently mixing buffer contents.
To reproduce the problem you can modify PaintView.mm inside the MGLPaint project this way:
- Change the background color inside the erase function (for example set it to red);
- Add something like

    glEnable(GL_SCISSOR_TEST);
    glScissor(backingWidth / 4, backingHeight / 4, backingWidth / 2, backingHeight / 2);

after

[MGLContext setCurrentContext:context forLayer:glLayer];

at the beginning of renderLineFromPoint

You will see the screen flickering while drawing something.

![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-04-27 at 11 09 32](https://user-images.githubusercontent.com/52881070/80355731-bb6a9980-8878-11ea-88e3-02222f6a987a.png)

![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-04-27 at 11 10 11](https://user-images.githubusercontent.com/52881070/80355840-e05f0c80-8878-11ea-867d-8a1f52920ac8.png)

Regards.
Luca.

**Comment by kakashidinho** [comment]
This issue should be fixed in latest master commit. Can you try again?
Note: For emulator pre 13.0, MetalANGLE will fallback to use native OpenGL backend since pre 13.0 simulator doesn't run Metal.
I haven't been actively maintaining the fallback mechanism, hence there was a blank screen when you tested. It should be fixed in the latest version also.

**Comment by lcarrettin** [comment]
The scissor is now working correctly, but there seems to be a scaling issue with simulators < 13 as you can see in these screenshots:

- Simulator 13
![Simulator Screen Shot - iPad Air 2 - 2020-04-28 at 11 15 07](https://user-images.githubusercontent.com/52881070/80472097-904d7c00-8944-11ea-9b39-070c19e57e5e.png)

- Simulator 12
![Simulator Screen Shot - iPad Air 2 - 2020-04-28 at 11 15 02](https://user-images.githubusercontent.com/52881070/80472138-9e9b9800-8944-11ea-8d39-4508b3f1ae81.png)

Thank you.

**Comment by kakashidinho** [comment]
Pre 13.0 emu is using native OpenGL and this backend code doesn’t support retina scaling. Native OpenGL backend is not my focus. Actually Google only updated this backend on their repo to support retina since a few days ago. In future, when I merge the code from upstream ANGLE repo, this issue should be fixed. For now, just expect that native OpenGL always draws at 1x resolution.

FYI, unlike emulator, on real devices, MetalANLE only fallbacks to native OpenGL if iOS version is below 11.0 and I think below 11.0 is rare since iOS users update quite frequently.

**Comment by lcarrettin** [comment]
OK,
Thanks a lot.
Regards.

Luca.
