### ISSUE TITLE
ITMS-90338: Non-public API usage when submitting to Apple Store

### ISSUE THREAD

**Issue by misl6** [kakashidinho/metalangle#13]
Hi, I tried to upload an App that uses `MetalANGLE.framework` to the Apple App Store, but this error is thrown.
```
ITMS-90338: Non-public API usage
- The app links to non-public libraries in Frameworks/MetalANGLE.framework/MetalANGLE: 
/System/Library/PrivateFrameworks/IOSurface.framework/IOSurface.
If method names in your source code match the private Apple APIs listed above,
altering your method names will help prevent this app from being flagged
in future submissions.
In addition, note that one or more of the above APIs may be located in a static library that was included with your app.
If so, they must be removed.
For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/ 
```

**Comment by kakashidinho** [comment]
This is probably due to IOSurface is only available since iOS 11.0. If your deployment target is less than 11.0, Apple will treat it as private usage. https://github.com/xamarin/xamarin-macios/issues/4257
IOSurface is only used by ANGLE's OpenGL backend. It has no use for Metal back-end atm. There are 2 options for now:
- You may set your app's deployment target to 11.0
- I will see if there is an easy way to omit IOSurface code from MetalANGLE.framework build. It actually has no use outside Chromium/browsers' WebGL implementation.

**Comment by kakashidinho** [comment]
I have disabled IOSurface code, this issue should be resolved now.

**Comment by misl6** [comment]
Thank you!
I can confirm that it fixed the issue.
