### ISSUE TITLE
Inconsistent pipeline state after shader change

### ISSUE THREAD

**Issue by RandomShaper** [kakashidinho/metalangle#15]
It's quite hard to explain this without being able to create an MRP. But I'll try. (This is for a GL ES 3 app running on iOS.)

In the project I'm integrating MetalANGLE with, I run across a situation when after a change of shader, the Metal pipeline was left in an inconsistent state: it had a buffer from the last state (when another shader was bound) that was not needed anymore so other buffers were "offset" by one place.

With that situation, even though there still was an 80-byte buffer to hold some uniform data, it wasn't the one such data was assigned too, but to another (the one that should have gone away from the previous pipeline state), which was smaller. Metal validation would complain.

The workaround for me was this (has worked perfectly for the time being, without causing any regressions):
```
angle::Result ContextMtl::setupDraw(...)
{
// [...]
            case DIRTY_BIT_RENDER_PIPELINE:
                // Already handled. See checkIfPipelineChanged().
                uniformBuffersDirty = true; // <--- This line is added by me
                break;
// [...]
```

I'm not opening a PR because I believe this is a hacky workaround rather than a proper fix. I haven't had time to investigate the exact point in the pipeline bookkeeping logic where it should realize the need for the change.

**Comment by kakashidinho** [comment]
This is a legit bug, although it's hard to create test cases to reproduce it. Since different shaders might have different uniform buffer's slots assigned by the translator.
Hence, when changing shader, the previously bound uniform buffer slot might not be valid for current shader anymore.

I think it's better to change the code inside `ProgramMtl`'s `setupDraw()` method instead of inside `ContextMtl::setupDraw()`, such as:
```
    if (uniformBuffersDirty || pipelineDescChanged)
    {
        ANGLE_TRY(updateUniformBuffers(context, cmdEncoder, pipelineDesc));
    }
```

Do you have a specific test case already available?
Thanks,

**Comment by RandomShaper** [comment]
I've tried your suggested patch instead of mine and it works just fine.

I'm sorry, but the case where I found the issue is quite intricate for me to try to extract a minimum reproduction case with my current bandwidth.

Thank you.
