### ISSUE TITLE
Compatibility with older iOS versions

### ISSUE THREAD

**Issue by mtehver** [kakashidinho/metalangle#2]
The project currently requires iOS version 11+. I guess that means that MetalANGLE is implemented using Metal 2. Is there any way to support older iOS versions? I think MoltenGL does this by dispatching GL calls to Apple GLES implementation on older devices. Would this be feasible to add? Thanks.

**Comment by kakashidinho** [comment]
Yes, I'm planning to do it (forward the calls to native GLES if IOS version is < 11.0). Didn't have time to do it since seems the demands are not high yet.
But this change won't require much, I think it won't take much time to finish.

**Comment by kakashidinho** [comment]
Added native GLES fallback to iOS 10 and below since revision [2eab375](https://github.com/kakashidinho/metalangle/commit/2eab37508d2d3a0134094e38b44d4c6f0d19dbbe)

**Comment by mtehver** [comment]
@kakashidinho Much appreciated, thanks!

**Comment by kakashidinho** [comment]
Hi,
Need to come back to this since there is a recent reported [issue](https://github.com/kakashidinho/metalangle/issues/13 ) regarding usage of native OpenGL backend in MetalANGLE. Did you face any issue related to App Store rejection due to MetalANGLE's usage of private library `IOSurface`?

ANGLE's native OpenGL backend currently uses IOSurface for their Chromium's WebGL implementation. Metal backend doesn't have any use for it for now. But since I needed to enable native OpenGL for older devices, this `IOSurface` code was unnecessarily enabled together with it.

**Comment by mtehver** [comment]
Hi,

so far I have used MetalANGLE just for development, so can not really comment on possible App Store rejection. But if it is so, then it definitely makes sense to drop IOSurface usage and bump requirements to iOS 11.

Thanks for commenting about this.
