### ISSUE TITLE
glReadPixels doesn't return

### ISSUE THREAD

**Issue by escamoteur** [kakashidinho/metalangle#45]
Hi,

any idea why the call to `glReadPixels` never comes back?

```objectivec
                glBindFramebuffer(GL_FRAMEBUFFER, currentTexture.fbo);

                CVPixelBufferLockBaseAddress([currentTexture pixelData], 0);
                void* buffer = (void*)CVPixelBufferGetBaseAddress([currentTexture pixelData]);

                 glReadPixels(0, 0, (GLsizei)[currentTexture width], (GLsizei)currentTexture.height, GL_RGBA, GL_UNSIGNED_BYTE, (void*)buffer);
                CVPixelBufferUnlockBaseAddress([currentTexture pixelData],0);
```

**Comment by escamoteur** [comment]
This is how I create the Pixelbuffer:

```objectivec
        NSDictionary* options = @{
          // This key is required to generate SKPicture with CVPixelBufferRef in metal.
          (NSString*)kCVPixelBufferMetalCompatibilityKey : @YES
        };

        CVReturn status = CVPixelBufferCreate(kCFAllocatorDefault, width, height,
                                              kCVPixelFormatType_32BGRA, (__bridge CFDictionaryRef)options, &_pixelData);
```

**Comment by kakashidinho** [comment]
I have no idea. I am not aware of any blocking issue in `MetalANGLE`.
Are you code available in any branch yet? I would like to pull it and debug. Your master branch doesn't seem to contain this piece of code to me.
Alternatively, you can find a way to debug into `MetalANGLE` on your own since you have its complete source code and can build it on your own.

**Comment by escamoteur** [comment]
Hi,

yeah I just debugged into it and it turned out it hags here
<img width="800" alt="grafik" src="https://user-images.githubusercontent.com/16635729/110955331-c7086700-8349-11eb-89fe-8b1f6e867bef.png">

it doesn't return from this call
```objectivec
 [metalBufferEntry.buffer waitUntilCompleted];
```
I can push my current state, but can you build a Flutter project? it won't do much if you only try to build the xcode project

**Comment by kakashidinho** [comment]
I can try to build flutter project. If i encountered any problem, I can ask you for directions.

**Comment by escamoteur** [comment]
current version is here https://github.com/FlutterGL/flutter_web_gl/tree/working_on_mac_version
I will help what I can :-)

**Comment by kakashidinho** [comment]
Just for a bit of understanding how you are using `MetalANGLE`. Are you using multiple contexts or multiple threads?

**Comment by escamoteur** [comment]
multiple threads with a shared context

**Comment by escamoteur** [comment]
but in my opinion I this two threads don't access MetalANGLE at the same time

**Comment by escamoteur** [comment]
actually its two contexts that one is created as shared context with the other, then each of them is made current from different threads

**Comment by kakashidinho** [comment]
I haven't debugged yet but let try to analyze the issue. Perhaps it can help me detect the issue with the multi context implementation in `MetalANGLE`. How are you using the two contexts?
1. Context 1 draw to FBO.
2. Context 2 read the FBO?

**Comment by kakashidinho** [comment]
Even though the above assumption shouldn't really cause any deadlock. But it would be great if you could provide a more detailed flow of your OpenGL usages.

**Comment by escamoteur** [comment]
actually it's exactly as you wrote, the Dart thread does all OpenGL calls for the rendering. When it has finished it sends a message to the objective thread to read the FBO so that Flutter can display it

**Comment by escamoteur** [comment]
https://github.com/FlutterGL/flutter_web_gl/blob/working_on_mac_version/macos/Classes/FlutterWebGlPlugin.m

and all OpenGL calls are here:

Initialisation:
https://github.com/FlutterGL/flutter_web_gl/blob/working_on_mac_version/lib/flutter_web_gl.dart
And usage:
https://github.com/FlutterGL/flutter_web_gl/blob/working_on_mac_version/example/lib/main.dart

**Comment by escamoteur** [comment]
Flutter itself also uses Metal to draw the UI, I don't know if that could make any problems

**Comment by kakashidinho** [comment]
No, I don't think so. Two of them use different Metal queue.

**Comment by kakashidinho** [comment]
nvm, fixed it. I didn't enable `macos_desktop` for flutter

**Comment by kakashidinho** [comment]
Ok, I know the issues. It's actually the multithreading issue. Standard test suite doesn't include multi-threading tests so it was hard to catch.
From your dart thread:
- you draw to FBO. Internally MetalANGLE records a command buffer. However when you call `t.signalNewFrameAvailable();` this command buffer is not committed to GPU yet. Normally `MetalANGLE` only commits the command buffer when there is a present call, `glFlush` call or any CPU transfers.

From the objective-C thread:
- Since it has to wait for the command buffer above to completed, however the command buffer hasn't been submitted to GPU yet. It was waiting forever.

I created a fix for your project by adding `glFlush` before `t.signalNewFrameAvailable();` here: https://github.com/FlutterGL/flutter_web_gl/pull/4/files

It should be OK for your project. However, I will need to re-design the wait `MetalANGLE` multi-thread & multi-context's command buffers more carefully in up-coming patches.

Thanks, your project is valuable to detect multi-threading issues like this. It would be valuable for official `ANGLE` also.

**Comment by kakashidinho** [comment]
This is the screenshot after the fix:
![Imgur](https://i.imgur.com/bsGCJka.png)

**Comment by escamoteur** [comment]
Thank you so much for your investigation. Yeah, makes absolute sense and as I have to call to the update Texture anyway the glFlush is no problem. thanks so much and I'm happy if the project can help with pinpointing such problem. 

I will probably come back to you to inestigate if there is a way to avoid this readpixel in future but for the moment its great that this works!
