### ISSUE TITLE
Redundant buffer/sampler bindings

### ISSUE THREAD

**Issue by TheSpydog** [kakashidinho/metalangle#5]
First off, I want to say thank you so much for working on this project! This is very exciting and I'm sure it will help many apps survive Apple's OpenGL deprecation. Also, huge thanks for releasing prebuilt binaries -- getting ANGLE set up can be really tricky, so thanks for removing that step!

On to the actual issue... I was testing a simple application with the latest macOS dylib release, and I noticed that the call stream contained many redundant (or unnecessary) buffer and sampler bindings. You can see a snippet of the call stream here:

<img width="523" alt="callstream" src="https://user-images.githubusercontent.com/8942401/75646369-6ebb6700-5c17-11ea-86f2-86dd324bfcd1.png">

Notice the various `setVertexBuffer:` calls. As far as I can tell, it's binding the same buffers over and over again, only adjusting the offset for each index between draw calls. Apple's best practices suggest using the [setVertexBufferOffset:atIndex:](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1515433-setvertexbufferoffset?language=objc) for changing the offset of an already-bound buffer. I wonder if that might yield some performance increases since redundant buffer bindings will not occur.

Similarly, the repeated `setFragmentSamplerState:` and `setVertexSamplerState:` calls seem to be entirely unnecessary since the sampler state and LOD clamp values never change between draw calls.

**Comment by kakashidinho** [comment]
Thanks for trying out.
It is interesting that Apple has another API to change the offset of buffer already bound. I also wonder why they do that. Probably to save command buffer space?
Yes, I will implement these redundant check in the future improvements. The samplerstate redundancy above is because each texture has its own sampler parameters per GLES 2 standard. But if they have same parameters, they will be cached as same sampler inside metal backend. I haven’t insert any check for duplicated sampler before setting it to command encoder either.
I also wondering if I do the redundancy check, whether it is necessary or not. Maybe it could help save the command buffer space. Maybe Metal framework already does the check. Actually in the metal back end, there is already a form of high level redundancy check, such that only a dirty vertex array object will force buffers rebinding. However it is not fine grained.

Btw, in new version, MetalANGLE can be built with xcode, I created an xcode project for both mac and iOS targets (still need to fetch dependencies through Google’s tools though). You can try to use it.

**Comment by kakashidinho** [comment]
I have implemented state caching in recent commit to prevent redundant state settings. I don't have any sample project that binds same buffers, different offsets repeatedly like yours. So you might want to give it a try to see if the redundancy you encountered has gone away.

**Comment by TheSpydog** [comment]
Just tested with my sample application, and indeed, all the redundancy is gone! The call stream is much cleaner now, and I'm noticing what appears to be a ~1ms frame time improvement from the last time I tested this application. (Which, admittedly, has been a while ago, so it's possible other improvements along the way are responsible for the improvement, but still!) Thank you for fixing this!
