### ISSUE TITLE
Crash when changing device orientation on iOS

### ISSUE THREAD

**Issue by mtehver** [kakashidinho/metalangle#6]
I seem to get a crash every time when I change my device orientation. The crash message is following (in MGLKitSampleApp):

-[MTLDebugRenderCommandEncoder setScissorRect:]:2702: failed assertion `(rect.x(0) + rect.width(2048))(2048) must be <= render pass width(1536)'

It seems that some internal state synchronisation is missing when the frame buffer size changes. I hit the same issue with my own tests also. I am testing using iPad Air 2, iOS 13.3.1.

**Comment by kakashidinho** [comment]
You are right, thanks. There is a bug. It's strange that the code can handle macOS's window resize but not iOS.

**Comment by kakashidinho** [comment]
One thing I noticed is that the crash is caused by the metal validation layer but this is actually a harmless crash, since the framebuffer will be correctly resized in the next frame. It is just that the immediate frame rendered at the moment the iOS's screen resize occurs will have incorrect size, hence metal validation layer complains and crashes the app immediately.
If you disable metal validation layer in the scheme settings, the crash won't happen anymore.
But I will fix this bug to make metal validation layer happy.
